const ACTIONS = {
    LOGIN: 'LOGIN',
    GET_TOKEN: 'GET_TOKEN',
    GET_USER: 'GET_USER',
    GET_MOVIE: 'GET_MOVIE',
    GET_RATING_MOVIE: 'GET_RATING_MOVIE',
    UPDATE_USER: 'UPDATE_USER',
    GET_ALL_GENRE: 'GET_ALL_GENRE',
    GET_REVIEW_MOVIE: 'GET_REVIEW_MOVIE'
}

export default ACTIONS